#pragma once
#include "com.h"
#include "stddef.h"
enum AvnKey
{
    AvnKeyNone = 0,
    AvnKeyCancel = 1,
    AvnKeyBack = 2,
    AvnKeyTab = 3,
    AvnKeyLineFeed = 4,
    AvnKeyClear = 5,
    AvnKeyReturn = 6,
    AvnKeyEnter = 6,
    AvnKeyPause = 7,
    AvnKeyCapsLock = 8,
    AvnKeyCapital = 8,
    AvnKeyHangulMode = 9,
    AvnKeyKanaMode = 9,
    AvnKeyJunjaMode = 10,
    AvnKeyFinalMode = 11,
    AvnKeyKanjiMode = 12,
    AvnKeyHanjaMode = 12,
    AvnKeyEscape = 13,
    AvnKeyImeConvert = 14,
    AvnKeyImeNonConvert = 15,
    AvnKeyImeAccept = 16,
    AvnKeyImeModeChange = 17,
    AvnKeySpace = 18,
    AvnKeyPageUp = 19,
    AvnKeyPrior = 19,
    AvnKeyPageDown = 20,
    AvnKeyNext = 20,
    AvnKeyEnd = 21,
    AvnKeyHome = 22,
    AvnKeyLeft = 23,
    AvnKeyUp = 24,
    AvnKeyRight = 25,
    AvnKeyDown = 26,
    AvnKeySelect = 27,
    AvnKeyPrint = 28,
};
